# Generated by Django 3.2.14 on 2022-07-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IBC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ibc', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'index_bolsa_caracas',
                'verbose_name_plural': 'indexes_bolsa_caracas',
                'db_table': 'ibc',
            },
        ),
    ]
